### ISSUE TITLE
Scene darker in build

### ISSUE THREAD

**Issue by AlexMeesters** [neon-age/AmplifyOcclusion-URP#1]
Hello! I was just testing your URP port, and I really like the effort you put into this.
Low settings of amplify occlusion look a lot better, less noise.

However it seems like builds are darker overall when using amplify occlusion. (Left one is the URP default SSAO)
As seen in the attached picture.

![urp-amplify-comparison](https://user-images.githubusercontent.com/16880385/220697578-de7743d6-e472-4a76-9c09-07c2b8c0cf16.jpg)

**Comment by neon-age** [comment]
Have you played with the settings? Such artifact is usually caused by small depth bias. Not sure if it looks different in Editor vs Build

**Comment by AlexMeesters** [comment]
Hey, so I've taken another stab at trying other settings and tinkering. And I've found the culprit.
Apparently if you have a toggled off render feature of SSAO in the Universal Renderer Data it causes this issue.
Looking like this:

![image](https://user-images.githubusercontent.com/16880385/221023506-9418a4f5-5a45-4264-8c30-bd3f3609087e.png)

Removing it from the list solves the issue fortunately.
I will close the issue as its a bug with Unity's SSAO.
